### PR TITLE
Allow notifications for systems without graphical capabilities

### PR DESCRIPTION
**Pull request by ammgws**
Solves #80. 

@frederickjh Would you like to test this?

### CODE REVIEW

**Comment by frederickjh** [comment]
@ammgws Thanks for your work on this. I set this up on a remote server to test.

I copied `done.fish` from your pull repository and installed `fishpkg/fish-humanize-duration`.  I then set:
```fish
# Set up done for remote notitfication via Telegram
set -U __done_allow_nongraphical 1
set -U __done_notification_command "ta \$title \$message"
```
Running a command longer than the default 5 seconds would generate a notification via my `ta.fish` function using Telegram.

I then increased the time before *done* sends a message to one minute with:
```fish
# in milliseconds time before done sends a message
set -U __done_min_cmd_duration 60000
```
This works as we discussed in #80.

I also added:
```fish
## Commands not to send done messages for. Accepts a regex
# all git commands, except push and pull.
# nano
set -U __done_exclude 'git (?!push|pull)|nano'
```
As who wants to be notified when the finish a long edit on a document?

Consider adding something like the following to the documentation section [Prevent specific commands from triggering notifications. Accepts a regex.](https://github.com/ammgws/done/tree/remotenotifications#prevent-specific-commands-from-triggering-notifications-accepts-a-regex) something like:

> Useful with ` set -U __done_allow_nongraphical 1` to prevent notifications for commands normally run interactively that you do not want to get *done* notifications for.

All in all a  :+1:, thanks!

**Comment by ammgws** [comment]
Good to know it's working!

I'll leave docs up to @franciscolourenco as I think it's fine

**Comment by frederickjh** [comment]
> I'll leave docs up to @franciscolourenco as I think it's fine

I found this [blog post](https://codeyarns.com/2013/06/29/how-to-get-notification-on-long-duration-command-completion-in-fish/) that says with **X11 forwarding** turned on for a SSH connection that that `notify-send` should send the alert on the local machine from the remote ssh session. 

I have not yet had time to test this with `done`  but the blog post says the code they are using ,which was added to `fish_prompt.fish`, should be added to the Fish shell on the remote host for this to work.

```fish
### Notify on long command completion

# If commands runs >= 10 seconds, notify user on completion
if test $CMD_DURATION
    if test $CMD_DURATION -gt (math "1000 * 10")
        set secs (math "$CMD_DURATION / 1000")
        notify-send "$history[1]" "Returned $status, took $secs seconds"
    end
end
```

If this works with `done` I think that it would be a good idea to add this to the documentation.

**Comment by ammgws** [comment]
If it works you should open another PR for adding it to the docs

**Comment by frederickjh** [comment]
> If it works you should open another PR for adding it to the docs

@ammgws If it was only that simple. I could not get this to work between two Ubuntu machines. One 16.04 and the other 18.04. I tried a number of settings locally in the `~/.ssh/config` file and the remote `/etc/ssh/sshd_config` but could not get this working even thought X11 forwarding is working to start a GUI program on the remote server and have it appear locally in a window to work on.

The notifications are sent via the DBUS. I tried setting the `DBUS_SESSION_BUS_ADDRESS` environmental variable but this too did not work. I have gone back to using `done` with my custom command that sends the notifications via a Telegram chat.

If someone smarter that me can figure this out so that it can be documented, so be it. :wink: :sunglasses: :angel:

**Comment by ammgws** [comment]
Closing due to inactivity
Sorry @frederickjh !

**Comment by franciscolourenco** [comment]
@ammgws What is the status of this? Is it working, reliable?

**Comment by ammgws** [comment]
I made this for @frederickjh, so will need his input

**Comment by frederickjh** [comment]
@franciscolourenco and @ammgws Sorry I didn't realize that more input was needed from me. I thought that my comments above were clear as to the status of this pull request.

To summarize what I stated above:

-  I tested this and it works. I am using a custom command (per the issue request #80) that posts to Telegram. 
- What I tried that did not work, which is outside the scope of the issue is using the X10 forwarding via SSH.
- I would add this pull request to the project, as it is documented and ready to be committed.

**Comment by frederickjh** [comment]
Actually there was one thing I thought should be added to the documentation. From above:

> Consider adding something like the following to the documentation section [Prevent specific commands from triggering notifications. Accepts a regex.](https://github.com/ammgws/done/tree/remotenotifications#prevent-specific-commands-from-triggering-notifications-accepts-a-regex) something like:
> 
> > Useful with ` set -U __done_allow_nongraphical 1` to prevent notifications for commands normally run interactively that you do not want to get _done_ notifications for.

**Comment by franciscolourenco** [comment]
@ammgws I've had a look at the PR and it looks good, so I would be up for merging this. Do you think it makes sense to add what @frederickjh to the docs, and if so would you mind doing it? Thanks!

**Comment by frederickjh** [comment]
Any reason @franciscolourenco this has not yet been merged in? Looks like this has everything to close #80.

**Comment by franciscolourenco** [comment]
Sorry, only was able to get to this.

**Comment by frederickjh** [comment]
No problem @franciscolourenco.  Sometimes life happens.

**Pull request merged**
