### PR TITLE
Add Hyprland Support

### PR DESCRIPTION
**Pull request by DrymarchonShaun**

### CODE REVIEW

**Comment by DrymarchonShaun** [comment]
_I think I did this right? Still new to pull requests on github._

**Comment by rehanzo** [comment]
Can confirm that this works.

**Review by franciscolourenco — APPROVED** [review]
@DrymarchonShaun thank you for your contribution!
@rehanzo thank you for testing!

**Comment by franciscolourenco** [comment]
Will be released with v1.17.9

**Pull request merged**
