### PR TITLE
Format code with `fish_indent`

### PR DESCRIPTION
**Pull request by ammgws**
Mainly just tabs converted to spaces.

### CODE REVIEW

**Comment by franciscolourenco** [comment]
fish_indent produces a different output for me. For example:
```
    set -g __done_initial_window_id ''
    set -q __done_min_cmd_duration
    or set -g __done_min_cmd_duration 5000
    set -q __done_exclude
    or set -g __done_exclude 'git (?!push|pull)'
    set -q __done_notify_sound
    or set -g __done_notify_sound 0
```

**Comment by ammgws** [comment]
Are you on fish master?

**Comment by ammgws** [comment]
Hmm, are you on fish master? 

The difference you're seeing is probably due to 15c50703ce446b131eb3154bfa3e9596d0bbd74f

**Comment by franciscolourenco** [comment]
3.0.2

**Comment by franciscolourenco** [comment]
I think it would make sense to use the formatter of the latest released version. What do you think?

**Comment by franciscolourenco** [comment]
or wait until the next version

**Comment by ammgws** [comment]
The next version will hopefully be out soon so I think it's OK to use the new formatter now.

Also, if we format with the 3.0.2 version it will remove the semicolons in favour of newlines, but when you run the new formatter after that it won't revert the change so I think it's better to just run the new formatter now and keep the current code style which the new formatter allows.

**Comment by franciscolourenco** [comment]
The only point of running the formatter is if we all use the same formatter all the time. I don't necessarily want to build and install fish from source, so the only formatter I would run is the one currently on stable.

That being said, you are the one doing the most changes lately, so no harm done. If you re-submit the PR without conflicts I would merge right away. Thanks!

**Comment by franciscolourenco** [comment]
thanks!

**Pull request merged**
