### PR TITLE
Option to enable notification in full screen

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
This PR for LINUX (ubuntu) allows to always have the notification, even in fullscreen when you're playing a game or watching a video. Just need to set the var in your config

I spent a unhealthy amount of time trying to make the "or" works -__- this is ridiculous

I also figured that it will prob cause an error when the variable is not set, so I hope you can fix it/show me how to fix it.

### CODE REVIEW

**Comment by franciscolourenco** [comment]
@BarbzYHOOL sorry only now got to this PR.

I'm not using linux daily. Are you saying that the notifications only get shown in fullscreen if `--urgency=critical` ?

**Comment by BarbzYHOOL** [comment]
Yes and I use my modification since then (useful when launching a command then starting a game :P)

**Comment by franciscolourenco** [comment]
@BarbzYHOOL thank you once again for the pull request and apologies for only now addressing it. I have one more question:

Does the notification style change for you, when `--urgency=critical` is used? 

Thanks

**Comment by ammgws** [comment]
I am not OP but I would say the answer to your question is yes.

For example, if you were using the `dunst` notification daemon, then the [default colour scheme](https://github.com/dunst-project/dunst/blob/master/dunstrc#L291-L297) sets critical notifications to have a red background.

**Comment by ammgws** [comment]
Just as a FYI, I'm using `sway` with `mako` for notifications, and adding `layer=overlay` to the mako config allows notifications to be shown over fullscreen applications.

**Comment by franciscolourenco** [comment]
I don't use Linux desktop on a daily basis, so don't really know what tools are usually available. Setting `--urgency=critical` seems like a workaround to achieve fullscreen notifications which has unrelated side effects. 

Therefore I'm inclined to no include this change, since the OP can use a custom command to add `--urgency=critical`
@ammgws The setup you describe is specific to sway, right?

**Comment by ammgws** [comment]
@franciscolourenco I am running with `sway` but `mako` should work with any `wlroots` based Wayland compositor.

I don't know what notification daemon OP is using but at least for `dunst`, it seems like it will only display notifications over fullscreen applications if their urgency is set to critical...

**Comment by franciscolourenco** [comment]
@BarbzYHOOL if we add this option we should probably call it `__done_notification_urgency_level`, and explain in the readme, that in linux it can be set it to critical to force notifications while in fullscreen mode.

**Comment by franciscolourenco** [comment]
Closing in favor of #72 
Thanks everyone!

**Comment by BarbzYHOOL** [comment]
thx guys, i trust ya

**Pull request closed without merging**
