### PR TITLE
Improve README instructions & presentation

### PR DESCRIPTION
**Pull request by jorgebucaran**
This PR improves the README presentation, indentation, and instructions.

- Replaces ~~fisherman~~ with Fisher
- Replaces <code>\`bash</code> with <code>\`fish</code>
- Replaces "plugin" with "package"
- Adds License section with a link to the LICENSE file
- Updates .travis.yml to use Fisher (although it's still broken because of https://github.com/jorgebucaran/fisher/issues/513)
- Adds a link to https://fishshell.com in dependencies section

@franciscolourenco The only thing I can't include to this PR is changing your GitHub repository tags. Could you change:

- `fish-plugin` to **`fish-packages`** and
- `fisherman` to `fisher` please?

Cheers.

### CODE REVIEW

**Comment by franciscolourenco** [comment]
I've edited the tags.

**Comment by jorgebucaran** [comment]
Thank you!

**Comment by jorgebucaran** [comment]
@franciscolourenco The repository description still says "plugin". Could you update that too for consistency?

**Comment by franciscolourenco** [comment]
Done, and thank you!

**Pull request merged**
