### PR TITLE
Add __done_humanize_duration, remove fishfile

### PR DESCRIPTION
**Pull request by IlanCosman**
This way is pure fish and removes dependencies. It is also much faster.

### CODE REVIEW

**Comment by ammgws** [comment]
I guess this would be one way to go especially since there's no indication that https://github.com/fishpkg/fish-humanize-duration/pull/2 will ever be merged.

**Comment by franciscolourenco** [comment]
This sounds good to me, thank you @IlanCosman and @ammgws – have you tested these changes?

**Comment by IlanCosman** [comment]
Yes, I have tested it. It doesn't display milliseconds though, but I can add that if you wish.

**Comment by franciscolourenco** [comment]
@IlanCosman I'm not even sure if it is useful to know the ms, but I suppose it wouldn't hurt either. Any takes on this @ammgws?

**Comment by ammgws** [comment]
@franciscolourenco If it is made to correctly handle durations over 60 hours then it should be good to go. That [same bug exists with humanize_duration itself](https://github.com/fishpkg/fish-humanize-duration/pull/1), and investigating that is what led me to rewrite it in https://github.com/fishpkg/fish-humanize-duration/pull/2. 

See wrong times given when the duration is longer than 60 hours:
```sh
>__done_humanize_duration 23000000
6h 23m 20s⏎
>__done_humanize_duration 230000000
3h 53m 20s⏎
```

**Comment by IlanCosman** [comment]
Fixed 😄

**Comment by franciscolourenco** [comment]
Thank you for the contribution!

**Pull request merged**
